spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300
      repositories:
        enabled: true


server:
  port: 8088

elasticsearch:
  ip: 127.0.0.1
  port: 9300
  pool: 5
  cluster:
    name: my-application
